root: true
env:
  node: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 'latest'

overrides:
  - files: 'src/scripts/**/*.js'
    env:
      browser: true
      es6: true

rules:
  indent: ['error', 2]
  linebreak-style: [2, unix]
  lines-between-class-members: [2, always, { exceptAfterSingleLine: true }]
  require-unicode-regexp: 0
  class-methods-use-this: 0
  implicit-arrow-linebreak: [error, below]
  object-curly-spacing: [2, always]
